name: Format Check

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: swift:6.2

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Git settings
        shell: bash
        run: |
          # https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install tools on container
        run: |
          apt update
          apt install -y make jq

      - name: Run make config
        run: make config

      - name: Check for config changes
        id: check_config_changes
        run: |
          if ! git diff --exit-code .swift-format; then
            git add .swift-format
            git commit -m "Update .swift-format configuration"

            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run make format
        run: make format

      - name: Check for format changes
        id: check_format_changes
        run: |
          if ! git diff --exit-code; then
            git add Plugins
            git commit -m "Update code formatting"

            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Check changes
        run: |
          if ! git diff --exit-code; then
            echo "::error::Code formatting changes detected. Please check the changes and commit them."
            exit 1
          fi

      - name: Push changes
        if: steps.check_config_changes.outputs.changed == 'true' || steps.check_format_changes.outputs.changed == 'true'
        run: git push origin

      - name: Success
        run: echo "✅ No formatting or configuration changes detected"
